FROM node:16-alpine3.12

LABEL version="1.0"
LABEL description="The React frontend for Nuspace Real Esate"

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

CMD [ "npm", "run", "start" ]